name: tiny_chat_server_core
description: A tiny chat server core written in dart that uses shelf_plus.
version: 1.0.0
repository: https://github.com/omegaui/tiny_chat_server_core

environment:
  sdk: '>=2.19.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  colored_print: ^1.0.0
  shelf_plus: ^1.5.1
  vm_service: ^9.4.0
  web_socket_channel: ^2.3.0